[build]
  publish = "site"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/urbano/productos"
  to = "/.netlify/functions/productos"
  status = 200

[[redirects]]
  from = "/api/urbano/productos/*"
  to = "/.netlify/functions/productos/:splat"
  status = 200

[[redirects]]
  from = "/api/urbano/imagenes"
  to = "/.netlify/functions/imagenes"
  status = 200

[[redirects]]
  from = "/api/urbano/imagenes/*"
  to = "/.netlify/functions/imagenes/:splat"
  status = 200
